name: macOS Testing

on:
  push:
    branches: [ "Secondmaster" ]
  pull_request:
    branches: [ "Secondmaster" ]

jobs:
  macos-job:
    runs-on: macos-latest
    steps:
      - name: Check macOS Version
        run: sw_vers
      - name: Run a Test Command
        run: |
          echo "This is a macOS virtual machine"
          system_profiler SPSoftwareDataType
